WindowView_MainFormClassName  = 'TFrmWindowView';
WindowView_Msg_MainFrom       = '{3D95192A-E7EC-4F04-AB69-F2296B5D3A31}';
WindowView_Msg_TestApp        = $001;
WindowView_Msg_Test_ResultOK  = $001;
WindowView_Msg_WindowHandle   = $002;
WindowView_Reg_Path           = 'SOFTWARE\YSoft\WindowView';
WindowView_RegKey_AppPath     = 'AppPath';
//CmdLine Param
WindowView_CLP_WindowHandle   = '-hwnd:';
